### ISSUE TITLE
precedent/list.jsonに一致しているKeyがある。

### ISSUE THREAD

**Issue by yakataN** [japanese-law-analysis/data_set#10]
事件名はあくまで事件名であり、それに対して裁判が複数ありうる
そのため、事件名・日付・trial_typeが一致するとJSONのIDが一致してしまう。

ex. 一致しているKey "令和3(行ケ)2_2022_2_21_LowerCourt"
https://www.courts.go.jp/app/hanrei_jp/detail4?id=91062
https://www.courts.go.jp/app/hanrei_jp/detail4?id=90984

**Comment by puripuri2100** [comment]
ありがとうございます
事件IDを別に振る必要がありそうです

**Comment by puripuri2100** [comment]
#14 での変更で解決されました
