### ISSUE TITLE
data_set/precedent/text_filesに行が欠落したテキストデータがある

### ISSUE THREAD

**Issue by suzaku33** [japanese-law-analysis/data_set#13]
タイトルの通り、行の欠落があるテキストデータがありました。
元のPDFを確認したところ、行頭がアラビア数字だとその行全部が欠落してしまうと思われます。ただ漢数字や括弧付き数字は問題ないようなので、全てのテキストデータに欠落があるわけではないと思われます。

欠落がある例
[令和1(わ)2456_2021_3_19_LowerCourt.txt](https://github.com/japanese-law-analysis/data_set/blob/master/precedent/text_files/%E4%BB%A4%E5%92%8C1(%E3%82%8F)2456_2021_3_19_LowerCourt.txt)
5と6, 58と59行目の間など
PDF: https://www.courts.go.jp/app/files/hanrei_jp/329/090329_hanrei.pdf

[令和2(う)479_2022_4_18_LowerCourt.txt](https://github.com/japanese-law-analysis/data_set/blob/master/precedent/text_files/%E4%BB%A4%E5%92%8C2(%E3%81%86)479_2022_4_18_LowerCourt.txt)
28と29, 100と101行目の間など
PDF: https://www.courts.go.jp/app/files/hanrei_jp/249/091249_hanrei.pdf

**Comment by puripuri2100** [comment]
行番号を消す処理が正常なときにも適用されてしまっているようです

**Comment by puripuri2100** [comment]
#14 での変更で解決されました
